let deferPrompt=null;window.addEventListener('beforeinstallprompt',(e)=>{e.preventDefault();deferPrompt=e;document.getElementById('btnInstall').hidden=false;});
document.getElementById('btnInstall').addEventListener('click',async()=>{if(deferPrompt){deferPrompt.prompt();deferPrompt=null;document.getElementById('btnInstall').hidden=true;}});
document.getElementById('btnShare').addEventListener('click',async()=>{const url=location.href;try{if(navigator.share)await navigator.share({title:document.title,url});else{await navigator.clipboard.writeText(url);alert('App link copied to clipboard');}}catch(e){}});
const $=(s)=>document.querySelector(s);const listEl=$('#list');const dlg=$('#dlg');const form=$('#form');const btnNew=$('#btnNew');const btnSave=$('#btnSave');const btnAddIcs=$('#btnAddIcs');const search=$('#search');const filterStatus=$('#filterStatus');const filterWhen=$('#filterWhen');const btnExport=$('#btnExport');const btnBackup=$('#btnBackup');const importJson=$('#importJson');const btnReports=$('#btnReports');const dlgReports=$('#dlgReports');let editingId=null;
function load(){try{return JSON.parse(localStorage.getItem('appointments')||'[]')}catch{return []}}function save(arr){localStorage.setItem('appointments',JSON.stringify(arr));render();}function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7);}
function render(){const q=search.value.trim().toLowerCase();const status=filterStatus.value;const when=filterWhen.value;const now=new Date();const todayStr=now.toISOString().slice(0,10);
const items=load().filter(a=>{const hay=`${a.client} ${a.phone||''} ${a.pet||''} ${a.notes||''}`.toLowerCase();if(q && !hay.includes(q))return false;if(status!=='all' && a.status!==status)return false;
if(when!=='all'){const d=a.date||'';if(when==='today' && d!==todayStr)return false;if(when==='upcoming' && d<todayStr)return false;if(when==='past' && d>=todayStr)return false;}return true;
}).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));listEl.innerHTML=items.map(cardHTML).join('')||`<p style="text-align:center;color:#6b7280;margin-top:20px">No appointments yet. Tap <b>+ New Appointment</b> to add one.</p>`;}
function cardHTML(a){const badge=`<span class="badge ${a.status}">${a.status[0].toUpperCase()+a.status.slice(1)}</span>`;const paid=a.paid==='yes'?'✅ Paid':'❌ Unpaid';const when=`${a.date||''} ${a.time||''}`.trim();
return `<article class="card" data-id="${a.id}"><header><h3>${escapeHtml(a.client)} • ${escapeHtml(a.pet||'')}</h3>${badge}</header><div class="meta">
<span>📅 ${when}</span>${a.phone?`<span>📞 ${escapeHtml(a.phone)}</span>`:''}${a.service?`<span>✂️ ${escapeHtml(a.service)}</span>`:''}${a.price?`<span>💲 ${Number(a.price).toFixed(2)}</span>`:''}${a.location?`<span>📍 ${escapeHtml(a.location)}</span>`:''}<span>${paid}</span></div>
${a.notes?`<div class="notes">${escapeHtml(a.notes)}</div>`:''}<div class="actions">${a.phone?`<button onclick="smsReminder('${a.id}')">Text Reminder</button>`:''}<button onclick="editItem('${a.id}')">Edit</button><button onclick="togglePaid('${a.id}')">${a.paid==='yes'?'Mark Unpaid':'Mark Paid'}</button><button onclick="quickComplete('${a.id}')">Complete</button><button onclick="delItem('${a.id}')">Delete</button><button onclick="downloadIcs('${a.id}')">Add to Calendar</button></div></article>`;}
function escapeHtml(s){return (s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
btnNew.addEventListener('click',()=>{editingId=null;form.reset();$('#dlgTitle').textContent='New Appointment';dlg.showModal();});
btnSave.addEventListener('click',(e)=>{e.preventDefault();const data=Object.fromEntries(new FormData(form).entries());if(!data.client||!data.date||!data.time){alert('Client, date, and time are required.');return;}
const arr=load();if(editingId){const i=arr.findIndex(x=>x.id===editingId);if(i>-1)arr[i]={...arr[i],...data};}else{arr.push({id:uid(),created:new Date().toISOString(),...data});}save(arr);dlg.close();});
window.editItem=(id)=>{const a=load().find(x=>x.id===id);if(!a)return;editingId=id;$('#dlgTitle').textContent='Edit Appointment';for(const [k,v] of Object.entries(a)){const el=form.querySelector(`[name="${k}"]`);if(el)el.value=v;}dlg.showModal();};
window.delItem=(id)=>{if(!confirm('Delete this appointment?'))return;save(load().filter(x=>x.id!==id));};
window.togglePaid=(id)=>{const arr=load();const i=arr.findIndex(x=>x.id===id);if(i>-1){arr[i].paid=(arr[i].paid==='yes'?'no':'yes');save(arr);}};
window.quickComplete=(id)=>{const arr=load();const i=arr.findIndex(x=>x.id===id);if(i>-1){arr[i].status='completed';save(arr);}};
search.addEventListener('input',render);filterStatus.addEventListener('change',render);filterWhen.addEventListener('change',render);
// CSV Export
document.getElementById('btnExport').addEventListener('click',()=>{const rows=load();const headers=['id','created','client','phone','pet','breed','service','price','date','time','location','status','paid','notes'];const csv=[headers.join(',')].concat(rows.map(r=>headers.map(h=>csvEscape(r[h]??'')).join(','))).join('\n');const blob=new Blob([csv],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='appointments.csv';a.click();});
function csvEscape(v){const s=String(v).replace(/"/g,'""');return /[",\n]/.test(s)?`"${s}"`:s;}
// Backup/Restore JSON
document.getElementById('btnBackup').addEventListener('click',()=>{const data=JSON.stringify(load(),null,2);const blob=new Blob([data],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='appointments-backup.json';a.click();});
document.getElementById('importJson').addEventListener('change',async(e)=>{const f=e.target.files[0];if(!f)return;try{const text=await f.text();const data=JSON.parse(text);if(!Array.isArray(data))throw new Error('Invalid');save(data);alert('Restore complete');}catch(err){alert('Restore failed: '+err.message);}});
// Reports
document.getElementById('btnReports').addEventListener('click',()=>{renderReports();document.getElementById('dlgReports').showModal();});
function sum(a,f){return a.reduce((t,x)=>t+(+f(x)||0),0);}function renderReports(){const items=load();const completed=items.filter(a=>a.status==='completed');const paidRevenue=sum(completed.filter(a=>a.paid==='yes'),a=>a.price);const unpaid=sum(items.filter(a=>a.status!=='canceled'&&a.paid!=='yes'),a=>a.price);document.getElementById('rCompleted').textContent=String(completed.length);document.getElementById('rPaidRevenue').textContent='$'+paidRevenue.toFixed(2);document.getElementById('rUnpaid').textContent='$'+unpaid.toFixed(2);const now=new Date();const months=[];for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1);months.push(d.toISOString().slice(0,7));}const byMonth=months.map(m=>{const rows=completed.filter(a=>(a.date||'').startsWith(m));const revenue=sum(rows.filter(a=>a.paid==='yes'),a=>a.price);return {month:m,count:rows.length,revenue};});const wrap=document.getElementById('rMonthly');wrap.innerHTML=byMonth.map(r=>`<div class="row"><div>${r.month}</div><div>${r.count} appts</div><div>$${r.revenue.toFixed(2)}</div></div>`).join('');}
// SMS Reminder
function smsReminder(id){const a=load().find(x=>x.id===id);if(!a||!a.phone){alert('No phone number on file.');return;}const phone=String(a.phone).replace(/\D/g,'');const when=`${a.date||''} ${a.time||''}`.trim();const msg=encodeURIComponent(`Hi ${a.client}, reminder: ${a.service||'Dog nail service'} for ${a.pet||'your pet'} on ${when}. Reply to confirm.`);const url=`sms:${phone}&body=${msg}`;location.href=url;}
// ICS
function buildICS(a){const pad=n=>(n<10?'0':'')+n;const [Y,M,D]=(a.date||'').split('-').map(Number);const [h,m]=(a.time||'00:00').split(':').map(Number);const start=new Date(Y,(M||1)-1,D||1,h||0,m||0);const end=new Date(start.getTime()+30*60*1000);
const toUtc=(d)=>d.getUTCFullYear()+pad(d.getUTCMonth()+1)+pad(d.getUTCDate())+'T'+pad(d.getUTCHours())+pad(d.getUTCMinutes())+'00Z';const dtstamp=toUtc(new Date());const dtstart=toUtc(start);const dtend=toUtc(end);
const summary=`Dog Nail Service: ${a.pet?(a.pet+' • '):''}${a.client}`;const loc=a.location||'';const desc=`Service: ${a.service||''}\nPrice: ${a.price||''}\nPhone: ${a.phone||''}\nNotes: ${a.notes||''}`;
return `BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//KJ Appointments//EN\nBEGIN:VEVENT\nUID:${a.id}@kj-app\nDTSTAMP:${dtstamp}\nDTSTART:${dtstart}\nDTEND:${dtend}\nSUMMARY:${summary}\nLOCATION:${loc}\nDESCRIPTION:${desc}\nEND:VEVENT\nEND:VCALENDAR`;}
function downloadIcs(id){const a=load().find(x=>x.id===id);if(!a)return;const ics=buildICS(a);const blob=new Blob([ics],{type:'text/calendar'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`appointment-${a.id}.ics`;link.click();}
// SW
if('serviceWorker' in navigator){window.addEventListener('load',()=>{navigator.serviceWorker.register('sw.js').catch(console.warn);});}
render();