if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(console.warn));}
const $=s=>document.querySelector(s);const catalogEl=$('#catalog'),cartItemsEl=$('#cartItems'),subtotalEl=$('#subtotal'),taxEl=$('#tax'),totalEl=$('#total'),taxRateLabel=$('#taxRateLabel');
const btnClearCart=$('#btnClearCart'),btnSettings=$('#btnSettings'),btnHistory=$('#btnHistory'),btnCash=$('#btnCash'),btnDebit=$('#btnDebit'),btnShareReceipt=$('#btnShareReceipt'),btnExport=$('#btnExport');
const dlgCash=$('#dlgCash'),dlgDebit=$('#dlgDebit'),dlgSettings=$('#dlgSettings'),dlgHistory=$('#dlgHistory');const formCash=$('#formCash'),formDebit=$('#formDebit'),formSettings=$('#formSettings');
const btnOpenStripe=$('#btnOpenStripe'),btnCompleteCash=$('#btnCompleteCash'),btnCompleteDebit=$('#btnCompleteDebit'),btnAddService=$('#btnAddService'),btnSaveSettings=$('#btnSaveSettings');
function load(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}}function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
const defaults={biz:"KJ’s Mobile Dog Nail Services",taxRate:0,stripeLink:"",services:[{name:"Nail Trim",price:15,desc:"Basic trim."},{name:"Nail Grind",price:20,desc:"Smooth finish."},{name:"Trim + Grind",price:25,desc:"Both trim and grind."},{name:"Add-on: Paw Pad Shave",price:5,desc:"Add to any service."}]};
let settings=load('pos_settings',defaults);let cart=load('pos_cart',[]);let history=load('pos_history',[]);
function renderCatalog(){const items=settings.services||[];catalogEl.innerHTML=items.map((s,i)=>`<article class="card"><header><h3>${escapeHtml(s.name)}</h3><div class="price">$${(+s.price||0).toFixed(2)}</div></header><div class="desc">${escapeHtml(s.desc||'')}</div><div class="actions"><button onclick="addToCart(${i})">Add</button></div></article>`).join('');}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function renderCart(){const rows=cart.map((it,idx)=>`<div class="cartItem"><div>${escapeHtml(it.name)}</div><div>$${(+it.price).toFixed(2)}</div><div class="qty"><button onclick="decreaseQty(${idx})">−</button><span>${it.qty}</span><button onclick="increaseQty(${idx})">+</button></div><div>$${(it.qty*it.price).toFixed(2)}</div></div>`).join('');cartItemsEl.innerHTML=rows||'<div style="color:#6b7280">Cart is empty.</div>';recalcTotals();}
function recalcTotals(){const sub=cart.reduce((t,x)=>t+x.qty*x.price,0);const tax=sub*((+settings.taxRate||0)/100);const total=sub+tax;subtotalEl.textContent='$'+sub.toFixed(2);taxEl.textContent='$'+tax.toFixed(2);totalEl.textContent='$'+total.toFixed(2);taxRateLabel.textContent=(+settings.taxRate||0)+'%';return {sub,tax,total};}
window.addToCart=(i)=>{const s=settings.services[i];if(!s)return;const j=cart.findIndex(x=>x.name===s.name&&+x.price===+s.price);if(j>-1)cart[j].qty+=1;else cart.push({name:s.name,price:+s.price||0,qty:1});save('pos_cart',cart);renderCart();};
window.increaseQty=(i)=>{cart[i].qty++;if(cart[i].qty<1)cart[i].qty=1;save('pos_cart',cart);renderCart();};window.decreaseQty=(i)=>{cart[i].qty--;if(cart[i].qty<=0)cart.splice(i,1);save('pos_cart',cart);renderCart();};
btnClearCart.addEventListener('click',()=>{cart=[];save('pos_cart',cart);renderCart();});
btnSettings.addEventListener('click',()=>{formSettings.biz.value=settings.biz||'';formSettings.taxRate.value=settings.taxRate??0;formSettings.stripeLink.value=settings.stripeLink||'';renderServicesEditor();dlgSettings.showModal();});
function renderServicesEditor(){const wrap=document.querySelector('#servicesEditor');wrap.innerHTML='';(settings.services||[]).forEach((s,idx)=>{const div=document.createElement('div');div.className='card';div.innerHTML=`<div class="grid"><label>Name<input data-i="${idx}" data-k="name" value="${escapeHtml(s.name)}"></label><label>Price ($)<input data-i="${idx}" data-k="price" type="number" step="0.01" min="0" value="${(+s.price||0)}"></label><label class="full">Description<textarea data-i="${idx}" data-k="desc" rows="2">${escapeHtml(s.desc||'')}</textarea></label></div><div class="actions"><button data-i="${idx}" data-del="1" class="ghost">Remove</button></div>`;wrap.appendChild(div);});wrap.querySelectorAll('input,textarea').forEach(el=>{el.addEventListener('input',()=>{const i=+el.dataset.i;const k=el.dataset.k;let v=el.value;if(k==='price')v=+v||0;settings.services[i][k]=v;});});wrap.querySelectorAll('button[data-del]').forEach(btn=>{btn.addEventListener('click',()=>{const i=+btn.dataset.i;settings.services.splice(i,1);renderServicesEditor();});});}
btnAddService.addEventListener('click',()=>{settings.services.push({name:"New Service",price:0,desc:""});renderServicesEditor();});
btnSaveSettings.addEventListener('click',(e)=>{e.preventDefault();settings.biz=formSettings.biz.value||defaults.biz;settings.taxRate=+formSettings.taxRate.value||0;settings.stripeLink=formSettings.stripeLink.value||'';save('pos_settings',settings);renderCatalog();recalcTotals();dlgSettings.close();});
btnHistory.addEventListener('click',()=>{renderHistory();dlgHistory.showModal();});
function renderHistory(){const wrap=$('#historyList');if(!history.length){wrap.innerHTML='<div style="color:#6b7280">No sales yet.</div>';return;}wrap.innerHTML=history.slice().reverse().map(h=>{const items=h.items.map(x=>`${x.qty}× ${escapeHtml(x.name)} ($${(+x.price).toFixed(2)})`).join(', ');return `<div class="historyItem"><div><b>${h.method.toUpperCase()}</b> • $${h.total.toFixed(2)} • ${new Date(h.time).toLocaleString()}</div><div>${items}</div>${h.ref? `<div>Ref: ${escapeHtml(h.ref)}</div>`:''}</div>`;}).join('');}
btnCash.addEventListener('click',()=>{if(!cart.length){alert('Cart is empty.');return;}formCash.reset();$('#changeDue').textContent='$0.00';formCash.tendered.addEventListener('input',()=>{const {total}=recalcTotals();const tend=+formCash.tendered.value||0;const change=Math.max(0,tend-total);$('#changeDue').textContent='$'+change.toFixed(2);},{once:false});dlgCash.showModal();});
btnCompleteCash.addEventListener('click',(e)=>{e.preventDefault();const {sub,tax,total}=recalcTotals();history.push({method:'cash',sub,tax,total,items:cart,ref:'',time:new Date().toISOString()});save('pos_history',history);cart=[];save('pos_cart',cart);renderCart();dlgCash.close();shareReceipt();});
btnDebit.addEventListener('click',()=>{if(!cart.length){alert('Cart is empty.');return;}dlgDebit.showModal();});
btnOpenStripe.addEventListener('click',()=>{if(settings.stripeLink){window.open(settings.stripeLink,'_blank');}else alert('Add a Stripe Payment Link in Settings first.');});
btnCompleteDebit.addEventListener('click',(e)=>{e.preventDefault();const ref=formDebit.ref.value||'';const {sub,tax,total}=recalcTotals();history.push({method:'debit',sub,tax,total,items:cart,ref,time:new Date().toISOString()});save('pos_history',history);cart=[];save('pos_cart',cart);renderCart();dlgDebit.close();shareReceipt();});
btnShareReceipt.addEventListener('click',()=>shareReceipt());
function shareReceipt(){const last=history[history.length-1];if(!last)return;const lines=[];lines.push(settings.biz);lines.push('Receipt '+new Date(last.time).toLocaleString());lines.push('Method: '+last.method.toUpperCase());lines.push('Items:');last.items.forEach(x=>lines.push(`  ${x.qty}× ${x.name} @ $${(+x.price).toFixed(2)} = $${(x.qty*x.price).toFixed(2)}`));lines.push(`Subtotal: $${last.sub.toFixed(2)}`);lines.push(`Tax: $${last.tax.toFixed(2)}`);lines.push(`Total: $${last.total.toFixed(2)}`);if(last.ref)lines.push(`Ref: ${last.ref}`);const text=lines.join('\n');if(navigator.share){navigator.share({title:'Receipt',text});}else{navigator.clipboard.writeText(text).then(()=>alert('Receipt copied to clipboard'));}}
btnExport.addEventListener('click',()=>{const rows=history;const headers=['time','method','subtotal','tax','total','ref','items'];const csv=[headers.join(',')].concat(rows.map(r=>{const itemStr=r.items.map(x=>`${x.qty}x ${x.name} @$${(+x.price).toFixed(2)}`).join(' / ').replace(/"/g,'""');return [r.time,r.method,r.sub,r.tax,r.total,r.ref||'',`"${itemStr}"`].join(',');})).join('\n');const blob=new Blob([csv],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sales-history.csv';a.click();});
renderCatalog();renderCart();